# Generated by Django 3.2.16 on 2023-01-17 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bac',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pseudo_bac', models.CharField(max_length=15, null=True, verbose_name='Pseudo Bac')),
                ('serie_bac_fr', models.CharField(choices=[('SE', 'Sciences Experimentales'), ('TM', 'Technique Mathématique'), ('MATH', 'Mathématique'), ('GE', 'Gestion et Economie'), ('LPH', 'Lettres et Philosophie'), ('LLE', 'Lettres et Langues Etrangères'), ('SNV', 'Science de la Nature et de la Vie'), ('LSH', 'Lettres et Sciences Humaines'), ('TC', 'Technique Comptable'), ('FM', 'Fabrication Mécanique'), ('ELECT', 'Electronique'), ('ELECTROTECH', 'Electrotechnique'), ('CHIMIE', 'Chimie'), ('TPB', 'Travaux Publiques et Batiments'), ('ETR', 'Bac Etranger'), ('Autre', 'Autre')], max_length=80, verbose_name='Serie du Bac')),
            ],
        ),
        migrations.CreateModel(
            name='Domaines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_domaine', models.CharField(help_text='Entrer le code du domaine', max_length=3, verbose_name='code du domaine')),
                ('intitule_domaine_fr', models.CharField(max_length=200, verbose_name='Intitulé du domaine (En latin) ')),
                ('intitule_domaine_ar', models.CharField(max_length=200, verbose_name='Intitulé du domaine (En arabe)')),
                ('pseudo_domaine', models.CharField(max_length=8, null=True, verbose_name='Pseudo code du domaine ')),
            ],
        ),
        migrations.CreateModel(
            name='Etablissements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_etablissement', models.CharField(help_text="Le code de l'établissement exemple:UMAB", max_length=10, verbose_name='Code établissement')),
                ('intitule_etabilissement_fr', models.CharField(max_length=200, verbose_name="Intitulé de l'établissement (en latin)")),
                ('intitule_etablissement_ar', models.CharField(max_length=200, verbose_name="Intitulé de l'établissement (en arabe)")),
                ('nature_etablissement', models.CharField(choices=[('UN', 'Université'), ('CU', 'Centre Universitaire'), ('ENS', 'Ecole Nationale Supérieure'), ('ENRS', 'Ecole Normale Supérieure'), ('IN', 'Institut Nationale')], max_length=4, verbose_name="Nature de l'établissement")),
                ('site_etablissement', models.CharField(max_length=200, verbose_name="Site de l'établissement")),
            ],
        ),
        migrations.CreateModel(
            name='Facultes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_faculte', models.CharField(help_text='Entrer le code de la faculté', max_length=8, verbose_name='Code de la faculté')),
                ('intitule_faculte_fr', models.CharField(max_length=200, verbose_name='Intitulé de la faculté (en latin)')),
                ('intitule_faculte_ar', models.CharField(max_length=200, verbose_name='Intitulé de la faculté (en arabe)')),
                ('statut', models.CharField(choices=[('FAC', 'Faculté'), ('INS', 'Institut')], max_length=3, verbose_name='Statut')),
                ('pseudo_faculte', models.CharField(max_length=8, verbose_name='Pseudo code de la faculté ')),
                ('etablissement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='conofo.etablissements', verbose_name='Etablissement')),
            ],
        ),
        migrations.CreateModel(
            name='Filiere_Bac',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moyenne_min', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('condition_matiere', models.TextField(max_length=100, null=True)),
                ('autorized', models.BooleanField(default=False, verbose_name='Filieres Autorisée')),
                ('priorite', models.CharField(choices=[('0', 'Priorité 0'), ('1', 'Priorité 1'), ('2', 'Priorité 2'), ('3', 'Priorité 3')], max_length=1, null=True, verbose_name='Priorité')),
                ('zone', models.CharField(default='27', max_length=30, verbose_name='Zone autorisée')),
                ('annee_bac', models.IntegerField(choices=[(2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022)], default=2019, verbose_name='Année Bac')),
                ('statut_filiere', models.CharField(choices=[('G', 'Gelée'), ('O', 'Ouverte')], default='O', max_length=1, verbose_name='Statut de la filière')),
                ('bac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conofo.bac')),
            ],
            options={
                'ordering': ['-moyenne_min', 'priorite'],
            },
        ),
        migrations.CreateModel(
            name='Filieres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_filiere', models.CharField(help_text='Entrer le code du filiere', max_length=3, verbose_name='Code du filiere')),
                ('intitule_filiere_fr', models.CharField(max_length=200, verbose_name='Intitulé du filiere (En latin)')),
                ('intitule_filiere_ar', models.CharField(max_length=200, null=True, verbose_name='Intitulé du filiere (En arabe)')),
                ('cycle', models.CharField(choices=[('L', 'LICENCE'), ('M', 'MASTER'), ('DM', 'Docteur en Médecine')], default='L', max_length=2, null=True, verbose_name='Cycle de filière')),
                ('pseudo_filiere', models.CharField(max_length=8, null=True, verbose_name='Pseudo code de la filiere ')),
                ('type_formation', models.CharField(choices=[('ACA', 'Académique'), ('PRO', 'Professionnalisante')], default='ACA', max_length=3, verbose_name='Type de la formation')),
                ('bac', models.ManyToManyField(through='conofo.Filiere_Bac', to='conofo.Bac')),
                ('domaine', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='conofo.domaines')),
                ('faculté', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='conofo.facultes')),
            ],
        ),
        migrations.CreateModel(
            name='Wilaya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_wilaya', models.IntegerField(verbose_name='Matricule Wilaya')),
                ('libelle_wilaya_fr', models.CharField(max_length=50, verbose_name='Wilya FR')),
                ('libelle_wilaya_ar', models.CharField(max_length=50, verbose_name='Wilya AR')),
            ],
        ),
        migrations.CreateModel(
            name='Specialites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_specialite', models.CharField(help_text='Entrer le code de la spécialité ', max_length=3, verbose_name='Code de la specialité ')),
                ('intitule_specialite_fr', models.CharField(max_length=200, verbose_name='Intitulé de la spécialité (En latin)')),
                ('intitule_specialite_ar', models.CharField(max_length=200, null=True, verbose_name='Intitulé de la spécialité (En arabe)')),
                ('cycle', models.CharField(choices=[('L', 'LICENCE'), ('M', 'MASTER'), ('DM', 'Docteur en Médecine')], default='L', max_length=2, null=True, verbose_name='Cycle de filière')),
                ('pseudo_specialite', models.CharField(max_length=8, null=True, verbose_name='Pseudo code de la specialité')),
                ('type_formation', models.CharField(choices=[('ACA', 'Académique'), ('PRO', 'Professionnalisante')], default='ACA', max_length=3, verbose_name='Type de la formation')),
                ('filiere', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='conofo.filieres')),
            ],
        ),
        migrations.AddField(
            model_name='filiere_bac',
            name='filiere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conofo.filieres'),
        ),
        migrations.AddField(
            model_name='etablissements',
            name='wilaya',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conofo.wilaya', verbose_name='Wilaya'),
        ),
        migrations.AddField(
            model_name='domaines',
            name='faculte',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='conofo.facultes'),
        ),
    ]
