# Generated by Django 3.2.16 on 2023-01-17 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conofo', '0003_auto_20230117_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='filieres',
            name='resume',
            field=models.TextField(default='Résumé de la formation', verbose_name='Détail de la filière'),
            preserve_default=False,
        ),
    ]
