# Generated by Django 3.2.16 on 2023-01-17 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conofo', '0004_filieres_resume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filieres',
            name='resume',
        ),
        migrations.AddField(
            model_name='filieres',
            name='debouchés_filière',
            field=models.TextField(default='test', verbose_name='Débouchés de la filière'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='filieres',
            name='description_filière',
            field=models.TextField(default='test', verbose_name='Description de la filière'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='filieres',
            name='email_responsable',
            field=models.EmailField(default='test@test.dz', max_length=50, verbose_name='E-mail responsable'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='filieres',
            name='responsable_formation',
            field=models.CharField(default='test@test.dz', max_length=50, verbose_name='Responsable de la formation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='specialites',
            name='debouchés_specialite',
            field=models.TextField(default='test', verbose_name='Débouchés de la spécialité'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='specialites',
            name='description_specialite',
            field=models.TextField(default='test', verbose_name='Description de la spécialité'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='specialites',
            name='email_responsable',
            field=models.EmailField(default='test@test.dz', max_length=50, verbose_name='E-mail responsable'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='specialites',
            name='responsable_formation',
            field=models.CharField(default='test', max_length=50, verbose_name='Responsable de la formation'),
            preserve_default=False,
        ),
    ]
