# Generated by Django 3.2.16 on 2023-01-18 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conofo', '0005_auto_20230117_2026'),
    ]

    operations = [
        migrations.CreateModel(
            name='unite_enseignement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_ue', models.CharField(max_length=3, verbose_name='Code UE ')),
                ('intitule_ue_fr', models.CharField(max_length=200, verbose_name='Intitulé UE (En latin)')),
                ('intitule_ue_ar', models.CharField(max_length=200, verbose_name='Intitulé UE (En arabe)')),
            ],
        ),
    ]
