# Generated by Django 3.2.16 on 2023-01-18 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conofo', '0006_unite_enseignement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unite_enseignement',
            name='code_ue',
        ),
        migrations.AddField(
            model_name='unite_enseignement',
            name='code_ue_ar',
            field=models.CharField(default='UE', max_length=3, verbose_name='Code UE (arabe)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unite_enseignement',
            name='code_ue_fr',
            field=models.CharField(default='UE', max_length=3, verbose_name='Code UE (latin)'),
            preserve_default=False,
        ),
    ]
