# Generated by Django 3.2.16 on 2023-01-18 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conofo', '0007_auto_20230118_0658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unite_enseignement',
            name='code_ue_ar',
            field=models.CharField(max_length=5, verbose_name='Code UE (arabe)'),
        ),
    ]
