# Generated by Django 3.2.16 on 2023-01-18 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conofo', '0008_alter_unite_enseignement_code_ue_ar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unite_enseignement',
            name='code_ue_ar',
            field=models.CharField(max_length=6, verbose_name='Code UE (arabe)'),
        ),
    ]
