# Generated by Django 3.2.16 on 2023-01-18 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conofo', '0009_alter_unite_enseignement_code_ue_ar'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Filiere_Bac',
            new_name='FiliereBac',
        ),
        migrations.RenameModel(
            old_name='unite_enseignement',
            new_name='UnitesEnseignements',
        ),
        migrations.CreateModel(
            name='Modules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_module', models.CharField(max_length=3, verbose_name='Code module')),
                ('intitule_module_fr', models.CharField(blank=True, max_length=50, verbose_name='Intitulé du module (En latin)')),
                ('intitule_module_ar', models.CharField(blank=True, max_length=50, verbose_name='Intitulé du module (En arabe)')),
                ('coef_module', models.IntegerField(verbose_name='Coef module')),
                ('unite_enseignement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='conofo.unitesenseignements', verbose_name='Unité Enseignement')),
            ],
        ),
    ]
