# Generated by Django 3.2.16 on 2023-01-18 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conofo', '0010_auto_20230118_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='modules',
            name='filiere',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='conofo.filieres', verbose_name='Filière'),
        ),
        migrations.AddField(
            model_name='modules',
            name='specialite',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='conofo.specialites', verbose_name='Spécialité'),
        ),
    ]
