# Generated by Django 3.2.16 on 2023-01-18 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conofo', '0011_auto_20230118_1318'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='modules',
            table='Modules',
        ),
    ]
