# Generated by Django 3.2.16 on 2023-01-18 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conofo', '0012_alter_modules_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bac',
            options={'verbose_name': 'Bac', 'verbose_name_plural': 'Bacs'},
        ),
        migrations.AlterModelOptions(
            name='domaines',
            options={'verbose_name': 'Domaine', 'verbose_name_plural': 'Domaines'},
        ),
        migrations.AlterModelOptions(
            name='etablissements',
            options={'verbose_name': 'Etablissement', 'verbose_name_plural': 'Etablissements'},
        ),
        migrations.AlterModelOptions(
            name='facultes',
            options={'verbose_name': 'Faculté', 'verbose_name_plural': 'Facultés'},
        ),
        migrations.AlterModelOptions(
            name='filieres',
            options={'verbose_name': 'Filière', 'verbose_name_plural': 'Filières'},
        ),
        migrations.AlterModelOptions(
            name='modules',
            options={'verbose_name': 'Module', 'verbose_name_plural': 'Modules'},
        ),
        migrations.AlterModelOptions(
            name='specialites',
            options={'verbose_name': 'Spécialité', 'verbose_name_plural': 'Spécialités'},
        ),
        migrations.AlterModelOptions(
            name='unitesenseignements',
            options={'verbose_name': 'Unité Enseignement', 'verbose_name_plural': 'Unités Enseignement'},
        ),
        migrations.AlterModelOptions(
            name='wilaya',
            options={'verbose_name': 'Wilaya', 'verbose_name_plural': 'Wilayas'},
        ),
        migrations.AlterModelTable(
            name='modules',
            table=None,
        ),
    ]
