# Generated by Django 3.2.16 on 2023-01-18 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conofo', '0013_auto_20230118_1729'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cycles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_cycle', models.CharField(max_length=3, verbose_name='Code du Cycle')),
                ('intitule_cycle_fr', models.CharField(max_length=25, verbose_name='Intitulé du Cycle (En latin)')),
                ('intitule_cycle_ar', models.CharField(max_length=25, verbose_name='Intitulé du Cycle (En arabe)')),
            ],
            options={
                'verbose_name': 'Cycle',
                'verbose_name_plural': 'Cycles',
            },
        ),
    ]
