# Generated by Django 3.2.16 on 2023-01-18 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conofo', '0014_cycles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filieres',
            name='cycle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='conofo.cycles', verbose_name='Cycle de filière'),
        ),
        migrations.AlterField(
            model_name='filieres',
            name='pseudo_filiere',
            field=models.CharField(default='a', max_length=8, verbose_name='Pseudo code de la filiere '),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='filieres',
            name='type_formation',
            field=models.CharField(choices=[('ACA', 'Académique'), ('PRO', 'Professionnalisante')], max_length=3, verbose_name='Type de la formation'),
        ),
    ]
