# Generated by Django 3.2.16 on 2023-01-18 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conofo', '0016_auto_20230118_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typesformation',
            name='intitule_TF_ar',
            field=models.CharField(max_length=35, verbose_name='Intitulé de type de formation (En arabe)'),
        ),
        migrations.AlterField(
            model_name='typesformation',
            name='intitule_TF_fr',
            field=models.CharField(max_length=35, verbose_name='Intitulé de type de formation (En latin)'),
        ),
    ]
