# Generated by Django 3.2.16 on 2023-01-18 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conofo', '0017_auto_20230118_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialites',
            name='cycle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='conofo.cycles', verbose_name='Cycle de spécialité'),
        ),
        migrations.AlterField(
            model_name='specialites',
            name='type_formation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='conofo.typesformation', verbose_name='Type de la formation'),
        ),
    ]
