# Generated by Django 3.2.16 on 2023-04-12 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conofo', '0018_auto_20230118_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etablissements',
            name='intitule_etabilissement_fr',
            field=models.CharField(max_length=200, verbose_name="Nom de l'établissement (en latin)"),
        ),
        migrations.AlterField(
            model_name='etablissements',
            name='intitule_etablissement_ar',
            field=models.CharField(max_length=200, verbose_name="Nom de l'établissement (en arabe)"),
        ),
    ]
